heat_template_version: 2013-05-23

description: |
  A simple Heat template that spins a web network and a web vm.

parameters:
  external_network_id:
    type: string
    label: ext-net
    description: UUID of a Neutron external network
    default: a6686ddc-37db-4562-9c2b-5c7b240b4f20

  web_image:
    type: string
    description: Name of image to use for servers
    default: ubuntu-14.04-server-amd64

  flavor:
    type: string
    description: Flavor of the image
    default: m1.small


resources:
  # Create the web logical switch and configure DHCP.
  web_network_01:
    type: OS::Neutron::Net
    properties:
      admin_state_up: true
      name: Web-1
  web_subnet_01:
    type: OS::Neutron::Subnet
    properties:
      name: web-subnet-01
      cidr: 172.16.10.0/24
      dns_nameservers: [192.168.110.10]
      enable_dhcp: true
      gateway_ip: 172.16.10.1
      network_id: { get_resource: web_network_01 }

  # Create the Instance
  web-svr-01:
    type: OS::Nova::Server
    properties:
      name: Web
      image: { get_param: web_image }
      flavor: { get_param: flavor }
      networks:
        - subnet_id: { get_resource: web_subnet_01 }

outputs:
  web-svr-01_private_ip:
    description: IP address of web-svr-01 in private network
    value: { get_attr: [ web-svr-01, first_address ] }
  web-svr-01_public_ip:
    description: Floating IP address of web-svr-01 in public network
    value: { get_attr: [ web-svr-01_floating_ip, floating_ip_address ] }

