heat_template_version: 2013-05-23

description: |
  Sample heat template to deploy container into Photon instance.
parameters:

  external_network_id:
    type: string
    label: ext-net
    description: UUID of a Neutron external network
    default: fdb92e61-75e4-47ef-9b74-557af5b6147d

  db_image:
    type: string
    description: Name of image to use for servers
    default: centos6.7

  web_image:
    type: string
    description: Name of image to use for servers
    default: centos6.7

  key_pair:
    type: string
    description: SSH Key Pair
    default: nness

  mysql_root_password:
    type: string
    description: MySQL root password
    hidden: true

  database_password:
    type: string
    description: MySQL user password
    hidden: true

  database_name:
    type: string
    label: Database name
    description: Name of the application database.

  database_user:
    type: string
    label: Database username
    description: Name of the database user.

  flavor:
    type: string
    label: Flavor
    description: Type of instance (flavor) to be used on the compute instance.
    default: m1.small

resources:
  # Create the web logical switch and configure DHCP.
  db_net:
    type: OS::Neutron::Net
    properties:
      admin_state_up: true
      name: db-net
  db_subnet:
    type: OS::Neutron::Subnet
    properties:
      name: db-subnet
      cidr: 192.168.41.0/24
      dns_nameservers: [8.8.8.8]
      enable_dhcp: true
      gateway_ip: 192.168.41.1
      network_id: { get_resource: db_net }
  # Create the router, add internal container interface, and add router uplink
  app_router_01:
    type: OS::Neutron::Router
    properties:
      admin_state_up: true
      name: app-router-01
  app_router_01_gw:
    type: OS::Neutron::RouterGateway
    properties:
      network_id: {get_param: external_network_id}
      router_id: { get_resource: app_router_01 }
  app_router_int0:
    type: OS::Neutron::RouterInterface
    properties:
      router_id: { get_resource: app_router_01 }
      subnet_id: { get_resource: db-subnet }

  # Create port(s) on container logical network.
  db1_port0:
    type: OS::Neutron::Port
    properties:
      admin_state_up: true
      network_id: { get_resource: db_net }

  # Provision instance
  db1:
    type: OS::Nova::Server
    properties:
      name: db1
      image: { get_param: db_image }
      flavor: { get_param: flavor }
      networks:
        - port: { get_resource: db1_port0 }
      user_data_format: RAW
      user_data:
        str_replace:
          params:
            __mysql_root_password__: { get_param: mysql_root_password }
            __database_name__: { get_param: database_name }
            __database_user__: { get_param: database_user }
            __database_password__: { get_param: database_password }
            #wc_notify: { get_attr: ['wait_handle', 'curl_cli'] }
          template: |
            #!/bin/bash

            # configure MySQL root password
            mysqladmin -u root password "__mysql_root_password__"

            # listen on all network interfaces
            sed -i "s/bind-address.*/bind-address = 0.0.0.0/" /etc/mysql/my.cnf

            # restart service
            service mysql restart

            # clone git repository for 3 Tier App
            git clone https://github.com/nvpnathan/threetier.git

            # create wordpress database
            mysql -u root --password="__mysql_root_password__" <<EOF
            CREATE DATABASE __database_name__;
            CREATE USER '__database_user__'@'localhost';
            SET PASSWORD FOR '__database_user__'@'localhost'=PASSWORD("__database_password__");
            GRANT ALL PRIVILEGES ON __database_name__.* TO '__database_user__'@'*' IDENTIFIED BY '__database_password__';
            CREATE USER '__database_user__'@'%';
            SET PASSWORD FOR '__database_user__'@'%'=PASSWORD("__database_password__");
            GRANT ALL PRIVILEGES ON __database_name__.* TO '__database_user__'@'%' IDENTIFIED BY '__database_password__';
            FLUSH PRIVILEGES;
            EOF
            # copy vio database
            mysql -u root -p "__database_name__" < threetier/db/vio.sql --password="__database_password__"

  # Attach floating IP
  container0_floating_ip:
    type: OS::Neutron::FloatingIP
    properties:
      floating_network_id: { get_param: external_network_id }
      port_id: { get_resource: container0_port0 }
outputs:
  container0_public_ip:
    description: Floating IP address of Container0 on the public network
    value: { get_attr: [ container0_floating_ip, floating_ip_address ] }
